### ISSUE TITLE
Self-hosted instance not working

### ISSUE THREAD

**Issue by sprtm** [viktorkalyniuk/LiTranslate-iOS#2]
Using a self-hosted instance in the app does not work for me. Nothing happens at all when pressing 'Translate'. If I check the iOS app privacy report, my instance URL has not been registered, so it seems the app has not tried to connect. If I switch over to one of the preset instances, it works. I've tried with both domain and IP — same issue with both. My instance is only internal and not exposed to the internet.

**Comment by viktorkalyniuk** [comment]
Hello! Did you entered your instance in correct format? 

Correct format is: **https://** your-instance.com **/translate**  
Connection works only through https and don't forget /translate

**Comment by sprtm** [comment]
Oh, I missed those two details! I still can't get it to work, though. As my instance isn't public, I have no proper SSL cert. I'm using Caddy, acting as a reverse proxy and Caddy is issuing the cert using its internal, locally trusted CA. That'll work in a web browser, I can just trust the cert maually, or import it into macOS keychain. But still no luck in the app. I tried to manually install and trust the cert on the iPhone, but it didn't change anything. Would a self-signed cert be accepted by the app?

**Comment by viktorkalyniuk** [comment]
Although it might work without https especially for local connection. The most important part is **/translate** at the end. Can you please try without https but with /translate ? Currently i have no possibility for check it by myself.

**Comment by viktorkalyniuk** [comment]
http://your-instance.com/translate

**Comment by sprtm** [comment]
I just reverted my Caddy settings and disabled https again and then trying http:// my-instance/translate, but unfortunately, still nothing happens when I click 'Translate'. http:// my-instance/translate loads fine in a web browser (just wanted to doublecheck to rule out DNS and firewall issues).

**Comment by viktorkalyniuk** [comment]
I see. 
Thank you, I will try to fix this issue as soon as possible.

**Comment by viktorkalyniuk** [comment]
Hi @sprtm  ! 
I've just tested from iOS 16.1.2 with local instance running from the Docker & it works.
Correct URL is: **http://192.168.xx.xxx:5000/translate**

Check internal ip of your machine running libretranslate, **don't forget to specify correct port** (default is 5000) & "/translate" at the end.

It is also worth noting that LiTranslate when you save your local URL ask "to find and connect to devices on your local network" this need to be allowed for local connection. If you refused earlier you can allow it in iPhone Settings>LiTranslate>Local Network or reinstall the application. 

You can also try only Docker for libretranslate instance.
_Linux/MacOS: ./run.sh [args] Windows: run.bat [args]_

Check also the connection to your local instance through the browser from your smartphone on which LiTranslate is installed.
If this does not help please specify your iOS version i will try to find a solution.

**Comment by sprtm** [comment]
I got it working now with http://10.0.x.x:5000/translate! For some reason the app does like http://internal-domain/translate. But the same URL works fine in web browsers and with curl — tried both from my iPhone and Mac. But maybe the issue is on my side with my setup.

Just some background details:
I'm running libretranslate with Docker on a Debian 11 machine. http://10.0.x.x:5000 is then proxied to http://internal-domain with Caddy.

But using the IP in the app is perfectly fine for me, so no need to dig deeper into this. Thanks for looking into it, and thanks for a great app!
